steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/vuepress/cgodwin-io:tag1', '.' ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/vuepress/cgodwin-io:tag1'
