export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"Blog Home","icon":"home","type":"home","readingTime":{"minutes":0,"words":0},"excerpt":"","date":"2022-07-10T17:50:22.000Z"},["/index.html","/README.md"]],
  ["v-79fdd481","/home.html",{"title":"Project home","icon":"home","type":"home","readingTime":{"minutes":0.17,"words":51},"excerpt":"This is an example of a project homepage. You can place your main content here. To use this layout, you need to set home: true in the page front matter. For related descriptions of"},["/home","/home.md"]],
  ["v-2b463433","/resume.html",{"title":"Certifications","type":"article","readingTime":{"minutes":4.33,"words":1299},"excerpt":"�R��\r\u0000\u0000�R��\r\u0000\u0000�H@\u0005\u0000\u0000\u0000\u0000�H@\u0005\u0000\u0000\u0000\u0000signInWith'), attempt = require('./attempt'), baseValues = require('./_baseValues'), customDefaultsAssignIn = require('./_customDefaultsAssignIn'), "},["/resume","/resume.md"]],
  ["v-2e0ad4b3","/toybox.html",{"title":"Toybox","icon":"style","type":"page","readingTime":{"minutes":0.05,"words":16},"excerpt":"Toybox These are fun things I'd like to showcase. JSLinux; JSLinux; JSLinux;"},["/toybox","/toybox.md"]],
  ["v-eec7c5b0","/posts/transitioning-from-coder-to-manager.html",{"title":"Transitioning from Coder to Manager","icon":"edit","type":"article","readingTime":{"minutes":0.64,"words":192},"excerpt":"Transitioning from Coder to Manager I recently got hired at Charles Schwab as a Full Time Employee(FTE). The position is a Management position which is more like a team lead. I hav","date":"2022-07-11T00:00:00.000Z","localizedDate":"July 10, 2022","category":["Management"],"tag":["software development","devsecops engineering"]},["/posts/transitioning-from-coder-to-manager","/posts/transitioning-from-coder-to-manager.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"Category","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"Tag","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"Articles","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"Encrypted","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"Slides","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"Star","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"Timeline","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-3383d934","/category/management/",{"title":"Management Category","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/management/index.html"]],
  ["v-920be1a8","/tag/software-development/",{"title":"software development Tag","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/software-development/index.html"]],
  ["v-6bc78abe","/tag/devsecops-engineering/",{"title":"devsecops engineering Tag","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/devsecops-engineering/index.html"]],
]
